core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/51)

DDF-983: updated the have the product cache enabled by default.

---

docs/src/main/resources/Integrating.adoc

correct typo in include directive
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/73)

DDF-1158: updated config file in adoc files.

---

admin/module/catalog-admin-module-sources/pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/76)

DDF-1176 Upgrade frontend-maven-plugin to 0.0.23

---

docs/pom.xml
docs/src/assembly/bin.xml
docs/src/main/resources/Integrating.adoc
solr/docs/pom.xml
solr/docs/src/assembly/bin.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/75)

DDF-1158: improved documentation module to include .zip file.

---

docs/src/main/resources/Extending.adoc
docs/src/main/resources/Integrating.adoc

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/78)

DDF-1096: Standardized image size within documentation files.

---

core/catalog-core-federationstrategy/pom.xml
core/catalog-core-federationstrategy/src/test/java/ddf/catalog/federation/impl/FederationStrategyTest.java
core/pom.xml

Fixed problem between JaCoCo and PowerMock and updated the coverage numbers back to what they were.
@shaundmorris, @stustison, please review.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/80)

DDF-1174: Fixed problem between JaCoCo and PowerMock

---

pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/84)

DDF-1192: Updated restlet to version 2.1.4 and Xalan to version 2.7.2 to address other high severity vulnerabilities.

---

core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualTokenizer.java
core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/ContextualPredicate.java
core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/PredicateTest.java

- Updated list of special characters.
- Added some comments.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/87)

DDF-1209 Unit test updates.

---

pom.xml

@shaundmorris
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/89)

DDF-1220 - Changed ddf-admin version to 1.1.1 for release build

---

docs/src/main/resources/Managing.adoc

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/91)

DDF-1096: added missing diagram to catalog/Managing docs

---

core/catalog-core-standardframework/pom.xml
core/catalog-core-urlresourcereader/pom.xml

A workaround for the noverify issue
@shaundmorris 
@lessarderic
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/96)

DDF-1191: Fixed issue with noverify option

---

catalog-app/src/main/resources/features.xml
core/catalog-core-app/src/main/resources/features.xml
core/catalog-core-cachecommands/pom.xml
core/catalog-core-cachecommands/src/main/java/org/codice/ddf/commands/cache/CacheCommands.java
core/catalog-core-cachecommands/src/main/java/org/codice/ddf/commands/cache/RemoveAllCommand.java
core/catalog-core-cachecommands/src/main/java/org/codice/ddf/commands/cache/RemoveCommand.java
core/catalog-core-cachecommands/src/main/java/org/codice/ddf/commands/cache/SearchCommand.java
core/catalog-core-cachecommands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
core/catalog-core-cachecommands/src/test/java/org/codice/ddf/commands/cache/TestRemoveAllCommand.java
core/catalog-core-cachecommands/src/test/java/org/codice/ddf/commands/cache/TestRemoveCommand.java
core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClient.java
core/catalog-core-standardframework/pom.xml
core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java
core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCacheMBean.java
core/pom.xml

@pklinef 
@kcwire 
@jlcsmith 
@emanns95
@jrnorth
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/98)

DDF-1074 cache mgmt

---

admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js

- The parameters configurable is no longer filtered out from the displayed configurables.
- Added a rebind method and updated the areas that were binding with the model to use it.  It correctly handles the binding, excluding configurables with cardinality > 0.
- Updated how the ConfigurationCollection is initialized so that the correct service and configuration are passed in.
- Added a 'beforeSave' trigger to the submitData function, so that configurables with cardinality > 0 can properly update themselves before the save occurs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/102)

DDF-1291 Updating Sources Tab to Display and Correctly Handle Configurables with Cardinality > 0

---

core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrFilterDelegate.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/108)

DDF-1264 added index for case sensitive wildcard searches

---

core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java

@wmcnalli @coyotesqrl
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/113)

DDF-1264 Added tests for wildcard searches with punctuation

---

admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js

@stustison 
@andrewkfiedler 
@djblue
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/111)

DDF-1326: Sets the id property along with shortname

---

admin/module/catalog-admin-module-sources/Gruntfile.js
admin/module/catalog-admin-module-sources/package.json
admin/module/catalog-admin-module-sources/pom.xml
admin/module/catalog-admin-module-sources/src/main/grunt/tasks/bower.js

@pklinef @andrewkfiedler 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/107)

DDF-1308 fixed issues with bower.json in sources admin module

---

core/catalog-core-cachecommands/src/main/java/org/codice/ddf/commands/cache/CacheCommands.java
core/catalog-core-cachecommands/src/test/java/org/codice/ddf/commands/cache/TestRemoveAllCommand.java
core/catalog-core-cachecommands/src/test/java/org/codice/ddf/commands/cache/TestRemoveCommand.java
core/catalog-core-standardframework/pom.xml
core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/SolrCacheMBean.java
core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java

@pklinef 
@kcwire 
@jlcsmith 
@jrnorth
Clean up for a previously merged PR
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/112)

DDF-1074 moved mbean interface out of impl package

---

content/docs/pom.xml
docs/pom.xml
solr/docs/pom.xml
spatial/docs/pom.xml
ui/docs/pom.xml

PR that fixes OWASP failures in nightly build.
@shaundmorris, please review and merge.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/119)

DDF-1345: Disabled vulnerability checks in docs projects

---

spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswSourceConfiguration.java
spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswFilterDelegate.java
spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java
spatial/csw/spatial-csw-source/src/main/resources/META-INF/spring/beans.xml
spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswCqlFilter.java
spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswFilterDelegate.java
spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswSource.java

- query type qname and prefix is configurable
- removed dependency on CSW Record MetacardType
- added query mapping for id attribute
@millerw8 @kcwire @wmcnalli @beyelerb @emanns95 @coyotesqrl
@wmcnalli is the hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/115)

DDF-1325: Made the CSW Source query type configurable

---

spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java

This PR replaces the (closed) PR DDF-1290, because [ticket DDF-1290](https://codice-ddf.atlassian.net/browse/DDF-1290) was written on the _test instance_ of codice jira.  This PR is associated with [ticket DDF-1346](https://codice.atlassian.net/browse/DDF-1346).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/120)

DDF-1346 must pass BigInteger to BigInteger.equals()

---

.gitignore

Big change, I know.
@pklinef 
@tbatieConnexta 
@jckilmer
@rzwiefel
@roelens8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/121)

DDF-1342 Missing .gitignore value from the ddf-ui merge into catalog.

---

admin/module/catalog-admin-module-sources/server-impl.js
admin/module/catalog-admin-module-sources/server.js
admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Source.view.js
admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceRow.handlebars

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/122)

DDF-1348 Show error message instead of blank for nameless configs

---

catalog-app/src/main/resources/features.xml
pom.xml
spatial/kml/spatial-kml-networklinkendpoint/pom.xml

Updated the karaf version to 2.4.3. Updated dependencies as needed. 
@mrmateo @shaundmorris @pklinef please verify these changes. 
@shaundmorris, once approved can you be the committer for this PR?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/125)

DDF-1224 Updated karaf to version 2.4.3

---

transformer/catalog-transformer-xml/pom.xml
transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/AbstractXmlTransformer.java
transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/GeometryTransformer.java
transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/XmlInputTransformer.java
transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/XmlMetacardTransformer.java
transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/XmlResponseQueueTransformer.java
transformer/catalog-transformer-xml/src/main/resources/OSGI-INF/blueprint/blueprint.xml
transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/IntegrationTest.java
transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestXmlInputTransformer.java
transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestXmlMetacardTransformer.java
transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestXmlResponseQueueTransformer.java

This is the catalog PR to demonstrate the Parser prototype in this [Platform PR](https://github.com/codice/ddf-platform/pull/73).
I'm comfortable with the changes and would like us to consider whether to merge them in as an improvement. Platform needs Javadocs, but otherwise I think this is relatively clean.
@menousek 
@pklinef 
@kcwire 
@lessarderic 
@stustison 
@brendan-hofmann
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/114)

DDF-1312 Prototype of XML transformers using new Parser bundle.

---

spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/Csw.java
spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java
spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/CswTransaction.java
spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/CswTransactionRequest.java
spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/InsertTransaction.java
spatial/csw/spatial-csw-endpoint/pom.xml
spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TransactionMessageBodyReader.java
spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TransactionRequestConverter.java
spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TestTransactionMessageBodyReader.java
spatial/csw/spatial-csw-schema-bindings/pom.xml
spatial/csw/spatial-csw-source/pom.xml
spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/RemoteCsw.java
spatial/csw/spatial-csw-transformer/pom.xml
spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
spatial/pom.xml

@jlcsmith @millerw8 @wmcnalli @pklinef @jrnorth @kguerriero @beyelerb @shane-voisard @emanns95
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/128)

DDF-1259 - added support for Insert via CSW Endpoint

---

core/catalog-core-cachecommands/pom.xml
core/catalog-core-cachecommands/src/main/java/org/codice/ddf/commands/cache/CacheCommands.java
core/catalog-core-cachecommands/src/main/java/org/codice/ddf/commands/cache/SearchCommand.java
core/catalog-core-cachecommands/src/test/java/org/codice/ddf/commands/cache/TestRemoveCommand.java
core/catalog-core-commands/pom.xml
core/catalog-core-standardframework/pom.xml
core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/SolrCacheMBean.java
core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java

@pklinef 
@millerw8 
@jlcsmith 
@kcwire 
@beyelerb 
@emanns95
@jrnorth 
@kguerriero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/127)

DDF-1262 added CQL query functionality to cache:search command

---

admin/module/catalog-admin-module-sources/pom.xml
admin/module/catalog-admin-module-sources/src/main/java/org/codice/ddf/catalog/admin/plugin/AdminSourcePollerServiceBean.java
admin/module/catalog-admin-module-sources/src/main/java/org/codice/ddf/catalog/admin/plugin/AdminSourcePollerServiceBeanMBean.java
admin/module/catalog-admin-module-sources/src/main/resources/OSGI-INF/blueprint/blueprint.xml
admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Service.js
admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Source.js
admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Status.js
admin/module/catalog-admin-module-sources/src/main/webapp/js/module.js
admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Source.view.js
admin/module/catalog-admin-module-sources/src/test/java/org/codice/ddf/catalog/admin/plugin/AdminSourcePollerTest.java
pom.xml
spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java
spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSource.java

Unit and Integration tests still need to be written, but reviewing can begin.
Requires DDF-1343 in DDF and DDF-Platform
@mverret will hero
@pklinef 
@brendan-hofmann 
@andrewkfiedler
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-catalog/126)

DDF-1343: Fixed availability in sources tab
